"""add file_changes

Revision ID: 0002_add_file_changes
Revises: 0001_initial_schema
Create Date: 2026-09-11

Closes a gap in the phase 1 data model that phase 3 planning exposed: ``commits`` records
only aggregate per-commit stats, and nothing links a commit to the individual files it
touched. Phase 4's headline capability -- ``complexity x recency-weighted churn`` -- is
computed per file, so without this table it has no input.

It lands in phase 3 rather than phase 4 because the clone is deleted when a scan ends.
The commit-to-file mapping exists only while the repository is on disk; a phase 4 that
needs it and does not have it must clone every target a second time.

Written by hand rather than autogenerated: autogenerate compares the models against a
live database, and none was reachable on the machine where this was authored. It follows
the conventions of 0001 -- named constraints via ``op.f``, VARCHAR enums with their CHECK
constraint (ADR 0002) -- and its upgrade/downgrade pair is exercised by
``tests/integration/test_migrations.py``, which runs in CI where PostgreSQL exists.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002_add_file_changes"
down_revision: str | None = "0001_initial_schema"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "file_changes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("commit_id", sa.Uuid(), nullable=False),
        # Nullable: a path touched in history may have no row in files, because it was
        # deleted or renamed before HEAD. Dropping those rows would understate churn on
        # exactly the files that churned most (C4).
        sa.Column("file_id", sa.Uuid(), nullable=True),
        sa.Column("path", sa.String(length=1024), nullable=False),
        # Nullable: git reports "-" for a binary diff, which is unknown, not zero.
        sa.Column("lines_added", sa.Integer(), nullable=True),
        sa.Column("lines_deleted", sa.Integer(), nullable=True),
        sa.Column(
            "change_type",
            sa.Enum(
                "added",
                "modified",
                "deleted",
                "renamed",
                name="change_type",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["commit_id"],
            ["commits.id"],
            name=op.f("fk_file_changes_commit_id_commits"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
            name=op.f("fk_file_changes_file_id_files"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_file_changes")),
    )
    op.create_index("ix_file_changes_commit_id", "file_changes", ["commit_id"], unique=False)
    op.create_index("ix_file_changes_file_id", "file_changes", ["file_id"], unique=False)


def downgrade() -> None:
    # Indexes and the CHECK constraint are dropped with the table.
    op.drop_table("file_changes")
